Environment=QA
Browser=Chromium
Framework=Playwright
Language=JavaScript (CommonJS)
Node.js=v22.15.0
npm=v10.9.2
OS=Windows
App.URL=https://next-gen-eob-ui-qa.teamlease.com/
Username=thr_recruiter
Password=12345
Login.Type=Keycloak two-step
Test.Runner=@playwright/test
Pattern=Page Object Model (POM)
Retries.Local=1
Retries.CI=2
Reporter=Allure + HTML + JSON
